# Server
server.port=0000
server.address=0.0.0.0

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Database
spring.datasource.url=jdbc:DB_VENDOR://DB_HOST:DB_PORT/DB_NAME
spring.datasource.username=DB_USER
spring.datasource.password=DB_PASSWORD
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# SSL
server.ssl.key-store=classpath:keystore-dev.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=KEYSTORE_PASSWORD
server.ssl.key-alias=springboot

# CORS (dev / preview)
cors.allowed-origins[0]=https://localhost:3000
cors.allowed-origins[1]=https://127.0.0.1:3000
cors.allowed-origins[2]=https://192.168.0.92:3000
cors.allowed-origins[3]=https://localhost:4173
cors.allowed-origins[4]=https://127.0.0.1:4173
cors.allowed-origins[5]=https://192.168.0.92:4173