# application name
spring.application.name=LINKLE

# profile name
spring.profiles.active=dev

# 날짜(Date/LocalDateTime)를 숫자(timestamp) 대신 ISO-8601 문자열(예: 2025-09-01T12:00:00)로 직렬화
spring.jackson.serialization.write-dates-as-timestamps=false

# false 설정 시 Service 계층에서 트랜잭션 내 데이터 모두 처리 후 세션 닫음
spring.jpa.open-in-view=false

# JWT 토큰 만료 시간 (ms : 1시간, 14일)
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=1209600000