# application name
spring.application.name=LINKLE

# profile name
spring.profiles.active=dev

# ??(Date/LocalDateTime)? ??(timestamp) ?? ISO-8601 ???(?: 2025-09-01T12:00:00)? ???
spring.jackson.serialization.write-dates-as-timestamps=false

#false ?? ? Service ???? ???? ? ??? ?? ?? ? ?? ??
spring.jpa.open-in-view=false